M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 17, 2023 at 09:23:07 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T09:23:07-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X4.2Y-3.5
X4.3Y-4.0
X4.5Y-3.3
X4.6Y-3.9
X4.8Y-3.5
X4.8Y-4.0
X4.9Y-3.2
X4.9Y-3.5
X4.9Y-3.8
X5.1Y-3.8
T2
X5.5Y-2.4524
X5.7Y-2.4524
T0
M30
